weather_in_city:
  path: /weather/{city}
  controller: App\Controller\WeatherController:cityAction
  requirements:
    city: \d+

weather_in_city_by_name:
  path: /weather/{name}
  controller: App\Controller\WeatherController:cityActionByName

app_logout:
  path: /login
